# Generated by Django 3.2.9 on 2021-11-25 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0002_alter_applyleave_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyleave',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontendapp.employee'),
        ),
    ]
