# Generated by Django 3.2.9 on 2021-11-26 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0003_applyleave_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applyleave',
            options={'managed': False},
        ),
    ]
